-- 16			Hours employees work for a plane owned by a corp
SELECT EMPLOYEE.PNAME as "Employee's Name", PLANE_TYPE.MODEL as 'Plane model', CORP.CNAME as 'Coorporation (Owner)', COUNT(SERVICE_RECORD.SHOUR) as 'Maintanace hours worked'
FROM EMPLOYEE
INNER JOIN PLANE_TYPE ON EMPLOYEE.WORKSON_MODEL = PLANE_TYPE.MODEL
INNER JOIN OWNERS ON OWNERS.Reg# = PLANE_TYPE.Reg#
INNER JOIN CORP ON OWNERS.OID = CORP.OID
INNER JOIN SERVICE_RECORD ON EMPLOYEE.SSN = SERVICE_RECORD.ESSN
GROUP BY EMPLOYEE.SSN, EMPLOYEE.PNAME, PLANE_TYPE.MODEL, CORP.CNAME
ORDER BY  COUNT(SERVICE_RECORD.SHOUR); 