-- 17		planes not owned by cooperations and no day shift employes have worked on these
SELECT PLANE_TYPE.Reg# as 'Plane registeration No', PLANE_TYPE.OF_TYPE as 'Plane Type', PERSON.PNAME as 'Owner', EMPLOYEE.ESHIFT as "Worker's shift" , SERVICE_RECORD.SWORK as 'Maintenance Work'
FROM PLANE_TYPE
INNER JOIN OWNERS ON PLANE_TYPE.Reg# = OWNERS.Reg#
INNER JOIN PERSON ON OWNERS.OID  = PERSON.OID
INNER JOIN EMPLOYEE ON PLANE_TYPE.MODEL = EMPLOYEE.WORKSON_MODEL
INNER JOIN SERVICE_RECORD ON EMPLOYEE.SSN = SERVICE_RECORD.ESSN
WHERE EMPLOYEE.ESHIFT != 'Morning' and EMPLOYEE.ESHIFT != 'Afternoon';
